### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bitinn** [bitinn/animeshot2#2]
A few things I might work on in future:

- [ ] V1 data importer
- [ ] User settings (custom username, connect multiple OAuth profile)
- [ ] Auto-restart on server reboot (upstart or systemd integration)
- [ ] Image proxy for external image
- [ ] User data export (static page or even custom sqlite)
- [ ] File uploader script
- [ ] Short GIF/MP4 support
- [ ] Shot editing

**Comment by Tsuki** [comment]
Can you resume/fix animeshot? Cloudflare show Error 526 Invalid SSL certificate

**Comment by bitinn** [comment]
@Tsuki you mean as2.bitinn.net? seems to be working fine without my intervention, probably a cloudflare issue.

**Comment by bitinn** [comment]
@Tsuki as.bitinn.net should redirect to as2.bitinn.net, if your browser is showing errors, google for a solution.

**Comment by Tsuki** [comment]
I got some image ref to as.bitinn.net/upload 
it cannot access anymore

**Comment by bitinn** [comment]
@Tsuki it's not safe to hotlink our uploads: we deleted hundreds of images since migration (we have a stricter rule in as2), so even if path rewrite has been done, some of your images might not work.

Also it depends on where you store these urls, if these data is under your control, you can batch update these url yourself (they still have the same id).

please open another issue to track your request.

**Comment by AkgunFatih** [comment]
remote file upload !

**Comment by wdpm** [comment]
Very much hope to see : `Short GIF/MP4 support` can be achieved
